### PR TITLE
Fix misc. typos

### PR DESCRIPTION
**Pull request by Caleb-Wishart**
Fixes typo's found across course content

### CODE REVIEW

**Comment by Caleb-Wishart** [comment]
Very descriptive commit messages I know...

In future I wonder if it is worth adding a `CONTRIBUTING.md` that contains a guide on formatting for such fixes.

**Comment by BraeWebb** [comment]
Thanks Caleb --- very brave to be reading ahead!

Could you please revert the changes to the week 3 practical so we can merge it without a conflict? Assuming that we've fixed all the mistakes in the week 3 practical now.

**Comment by Caleb-Wishart** [comment]
> Thanks Caleb --- very brave to be reading ahead!

Trying to get ahead while assignments are quiet.

> Could you please revert the changes to the week 3 practical so we can merge it without a conflict? > Assuming that we've fixed all the mistakes in the week 3 practical now.

I didn't take a deep look at the changes but have reverted that commit for you.

**Review by BraeWebb — APPROVED** [review]
LGTM

**Pull request merged**
